name: Buile Android App
on:
    push

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:

            - name: Set Version
              env:
                GRN: ${{ github.run_number }}
              run: echo "DYNAMIC_VERSION=$(($GRN+302))" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                java-version: '18'
                distribution: 'corretto'
                cache: gradle
              
            - name: Build
              run: |
                chmod +x gradlew
                ./gradlew build
