name: Release
on:
  workflow_dispatch

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:

      - name: Set Version
        env:
          GRN: ${{ github.run_number }}
        run: echo "DYNAMIC_VERSION=$(($GRN+302))" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
          cache: gradle

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}

      - name: Deploy to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: tv.dustypig.dustypig
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          debugSymbols: app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
          track: internal
          
